#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sismografoenlinea
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AspNetServicesDB")]
	public partial class Db_aspNetServicesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertalarmas(alarmas instance);
    partial void Updatealarmas(alarmas instance);
    partial void Deletealarmas(alarmas instance);
    partial void Insertmediciones(mediciones instance);
    partial void Updatemediciones(mediciones instance);
    partial void Deletemediciones(mediciones instance);
    #endregion
		
		public Db_aspNetServicesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AspNetServicesDBConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Db_aspNetServicesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Db_aspNetServicesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Db_aspNetServicesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Db_aspNetServicesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<alarmas> alarmas
		{
			get
			{
				return this.GetTable<alarmas>();
			}
		}
		
		public System.Data.Linq.Table<mediciones> mediciones
		{
			get
			{
				return this.GetTable<mediciones>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetEmailAddress")]
		public int GetEmailAddress([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string correo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreUsuario, correo);
			correo = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lecturasDelDia")]
		public int lecturasDelDia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> indice, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] ref string magnitud)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), indice, magnitud);
			magnitud = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lecturasDelDia_CantRegistros")]
		public int lecturasDelDia_CantRegistros([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] ref string magnitud)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), magnitud);
			magnitud = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarRegistrosMasActuales")]
		public int mostrarRegistrosMasActuales([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> indice, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] ref string magnitud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> antepenultimoid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), indice, magnitud, antepenultimoid);
			magnitud = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alarmas")]
	public partial class alarmas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _nombre;
		
		private string _desde;
		
		private string _hasta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndesdeChanging(string value);
    partial void OndesdeChanged();
    partial void OnhastaChanging(string value);
    partial void OnhastaChanged();
    #endregion
		
		public alarmas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desde", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string desde
		{
			get
			{
				return this._desde;
			}
			set
			{
				if ((this._desde != value))
				{
					this.OndesdeChanging(value);
					this.SendPropertyChanging();
					this._desde = value;
					this.SendPropertyChanged("desde");
					this.OndesdeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasta", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string hasta
		{
			get
			{
				return this._hasta;
			}
			set
			{
				if ((this._hasta != value))
				{
					this.OnhastaChanging(value);
					this.SendPropertyChanging();
					this._hasta = value;
					this.SendPropertyChanged("hasta");
					this.OnhastaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mediciones")]
	public partial class mediciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _magnitud;
		
		private int _tiempo;
		
		private System.DateTime _fecha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmagnitudChanging(int value);
    partial void OnmagnitudChanged();
    partial void OntiempoChanging(int value);
    partial void OntiempoChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    #endregion
		
		public mediciones()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magnitud", DbType="Int NOT NULL")]
		public int magnitud
		{
			get
			{
				return this._magnitud;
			}
			set
			{
				if ((this._magnitud != value))
				{
					this.OnmagnitudChanging(value);
					this.SendPropertyChanging();
					this._magnitud = value;
					this.SendPropertyChanged("magnitud");
					this.OnmagnitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiempo", DbType="Int NOT NULL")]
		public int tiempo
		{
			get
			{
				return this._tiempo;
			}
			set
			{
				if ((this._tiempo != value))
				{
					this.OntiempoChanging(value);
					this.SendPropertyChanging();
					this._tiempo = value;
					this.SendPropertyChanged("tiempo");
					this.OntiempoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
